name: toronto-shared-bike-postgresql

volumes:
  pgdata:
  # pgbackup:

networks:
  public-net:
    driver: bridge

services:
  postgresql-db:
    container_name: postgresql
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SecurePassword123}
      POSTGRES_DB: ${POSTGRES_DB:-toronto_shared_bike}
      PGDATA: ${PGDATA}
    volumes:
      - ./scripts/setup:/docker-entrypoint-initdb.d # scripts to run after setup
      - ./scripts:/scripts
      - ../data:/data
      - ../export:/export
      - pgdata:/var/lib/postgresql # persist data
    networks:
      - public-net # public for dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d toronto_shared_bike"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
